DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Purchases;


CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);



CREATE TABLE Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Purchases (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    nameproduct TEXT,
    quantity INTEGER,
    email TEXT NOT NULL,
    description TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);